:schedule:
  LeadStatusUpdateWorker:
    every: '10m'
  QuoteExpiryWorker:
    every: '3m'
  AdminStatusPanelWorker:
    every: '1440m'
  BranchLockedStatusUpdateWorker:
    every: '1440m'
  SoldPropertyUpdateWorker:
    cron: '0 0 * * *'
  AdsExpiryWorker:
    cron: '5 0 * * *'
  S3ImageCleanUpWorker:
    every: '1440m'

