:schedule:
  LeadStatusUpdateWorker:
    every: '10m'
  QuoteExpiryWorker:
    every: '3m'
  RentQuoteExpiryWorker:
    every: '3m'
  AdminStatusPanelWorker:
    every: '1440m'
  BranchLockedStatusUpdateWorker:
    every: '1440m'
  MobileOtpCleanupWorker:
    every: '60m'
  SoldPropertyUpdateWorker:
    cron: '0 0 * * *'
  BranchStatsWorker:
    cron: '10 1 * * *'
  AdsExpiryWorker:
    cron: '5 0 * * *'
  PanelDetailsWorker:
    cron: '20 0 * * *'
  S3ImageCleanUpWorker:
    every: '1440m'
  AdminDeassignMailshotPropertyWorker:
    cron: '30 0 * * *'
  AdminNotifyIncorrectPropertyWorker:
    cron: '6 0 * * *'

